http:
  port: "8081"

american:
  host: "training4-american-api-jionajoy.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "9c4a879a1b9a4fbdbadb4f53c9c0af2f"
  client_secret: "32c108694Ddd4B23A81545a3A274920d"

training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"
